runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /lib
  static_dir: app/lib

- url: /component
  static_dir: app/components

- url: /statics
  static_dir: app/statics

- url: /handlers.*
  login: required
  script: main.app

- url: /
  script: main.app
  login: required

- url: /.*
  login: required
  static_files: app/index.html
  upload: app/index.html

libraries:
- name: webapp2
  version: latest

  